server:
  port: 8080

spring:
  redis:
    database: 0
    password: 1qaz2wsx
    host: 127.0.0.1
    port: 6379

xcheck:
  controller-package: com.c.j.w.sample
  column-alias: startTime=开始时间, endTime=结束时间
  show-error-message: false